site_name: "Definizione ed integrazione processi di deploy attraverso automazione della promotion (pipeline)"
site_description: Definizione ed integrazione processi di deploy attraverso automazione della promotion (pipeline)
plugins: 
    - techdocs-core
markdown_extensions:
    - attr_list
nav:
    - Introduzione: "index.md"
    - Processo di Deploy in Ambiente di Sviluppo CDP: "02-processo-deploy.md"
    - Processi di Promotion: "03-processo-promtion.md"
