apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "linee-guida-documentazione"
  tags: [linee-guida]
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: user:rmarchetti rmarchetti@younified.it
  lifecycle: experimental