edit_uri: ""
site_name: "Linee Guida per l'implementazione dei test del codice"
site_description: Linee guida per la scrittura, manutenzione e gestione dei test automatici del codice all'interno dell'Ambiente di Sviluppo Sicuro
markdown_extensions: 
    - attr_list
plugins: 
    - techdocs-core
nav:
    - Introduzione: "index.md"
    - Politiche di Test: "02-politiche-test.md"
    - Implementazione dei Test: "03-implementazione-test.md"
    - Strategie di Riesecuzione dei Test: "04-strategie-riesecuzione.md"
    - Definizione del Perimetro dei Test per i Casi d'Uso: "05-perimetro-test.md"
    - Gestione dei Database per i Test: "06-db-test.md"
